DROP DATABASE IF EXISTS Students_Info;
CREATE DATABASE Students_Info;
USE Students_Info;

CREATE TABLE Students (
	StudentID INT AUTO_INCREMENT PRIMARY KEY,
	FirstName VARCHAR(50) NOT NULL,
	LastName VARCHAR(50) NOT NULL,
	Email VARCHAR(100) UNIQUE,
	EnrollmentDate DATE
);

CREATE TABLE Orders (
	OrderID INT UNIQUE AUTO_INCREMENT PRIMARY KEY,
	StudentID INT,
	OrderDate DATE,
	Total INT,
	FOREIGN KEY (StudentID) REFERENCES Students(StudentID) ON DELETE CASCADE ON UPDATE CASCADE
);
